version: '3.8'

volumes:
  redis-box:
    driver: ${VOLUMES_DRIVER}

services:
### REDIS BOX ##############################################
  redis-box:
    build:
      context: ${REDIS_HOST_PATH}
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: ${REDIS_BOX_CONTAINER_NAME}
    hostname: ${REDIS_BOX_HOSTNAME_NODE1}
    command: 'redis-cli --cluster create ${REDIS_NODES} --cluster-replicas 1 --cluster-yes'
    ports:
      - "${REDIS_BOX_HOST_PORT}:6379"
    environment:
      TZ: ${TZ}
    networks:
      frontend:
        ipv4_address: ${REDIS_BOX_FRONTEND_IP}
      backend:
        ipv4_address: ${REDIS_BOX_BACKEND_IP}
    depends_on:
      - "${REDIS_CONTAINER_NAME_NODE1}"
      - "${REDIS_CONTAINER_NAME_NODE2}"
      - "${REDIS_CONTAINER_NAME_NODE3}"
      - "${REDIS_CONTAINER_NAME_NODE4}"
      - "${REDIS_CONTAINER_NAME_NODE5}"
      - "${REDIS_CONTAINER_NAME_NODE6}"
      - "${REDIS_CONTAINER_NAME_NODE7}"
      - "${REDIS_CONTAINER_NAME_NODE8}"
      - "${REDIS_CONTAINER_NAME_NODE9}"