version: '3.8'

networks:
  backand:
    external: true

services:
  clickhouse:
    build:
      context: ./clickhouse
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
#      - ${CLICKHOUSE_CONFIG_PATH}/config.xml:/etc/clickhouse-server/config.xml:rw
#      - ${CLICKHOUSE_CONFIG_PATH}/users.xml:/etc/clickhouse-server/users.xml:rw
#      - ${CLICKHOUSE_LOG_PATH}:/var/log/clickhouse-server/
      - ${CLICKHOUSE_DATA_PATH}:/bitnami/clickhouse
    networks:
      backand:
        ipv4_address: ${CLICKHOUSE_IP}