version: '3.8'

networks:
  devops-network:
    name: devops-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.150.0/24
          gateway: 172.19.150.1
configs:
  gitlab:
    file: ./config/gitlab.rb
secrets:
  gitlab_root_password:
    file: ./config/root_password.txt
services:
  gitlab:
    build:
      context: ./gitlab
      args:
        - GITLAB_VERSION=${GITLAB_VERSION}
    container_name: gitlab
    hostname: 'zz.gitlab.com'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    ports:
      - '8929:8929'
      - '2224:22'
      - '8443:443'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '1gb'
    logging: 
      driver: "json-file"
      options: 
        max-size: "2g"
        max-file: "2"
    networks:
      devops-network:
        ipv4_address: ${GITLAB_IP}