version: "3.8"

networks:
  backand:
    external: true

services:
  etcd:
    build:
      context: ./etcd
    container_name: ${ETCD_NAME}
    hostname: ${ETCD_NAME}
    environment:
      - ETCDCTL_API=${ETCDCTL_API}
      - ENDPOINTS=${ETCD_ENDPOINTS}
    command:
      - --name=${ETCD_NAME}
      - --data-dir=/etcd_data
      - --initial-advertise-peer-urls=http://${ETCD_NAME}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://${ETCD_NAME}:2379
      - --heartbeat-interval=${ETCD_HEARTBEAT_INTERVAL}
      - --election-timeout=1250
      - --initial-cluster=${ETCD_CLUSTER}
      - --initial-cluster-state=${ETCD_CLUSTER_STATE}
      - --initial-cluster-token=${ETCD_TOKEN}
    ports:
      - "${ETCD_HOST_PORT}:2379"
      - "${ETCD_PORT_REVERSE}:2380"
    networks:
      backand:
        ipv4_address: ${ETCD_IP}
    volumes:
      - ${ETCD_DATA_PATH}:/etcd_data