version: '3.8'

networks:
  postgresql-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.0.0/24

services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    networks:
      postgresql-network:
        ipv4_address: 172.12.0.10
    volumes:
      - ./postgresql/data:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      postgresql-network:
        ipv4_address: 172.12.0.11
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgresql