version: '3.8'

networks:
  lanp-network:
    external: true

services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    networks:
      lanp-network:
        ipv4_address: ${POSTGRES_IP}
    volumes:
      - ./postgresql/data:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      lanp-network:
        ipv4_address: ${POSTGRES_ADMIN_IP}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgresql