version: '3.8'

networks:
  zookeeper-standalone-network:
    driver: bridge

services:
  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_NAME_1}
    hostname: ${ZOOKEEPER_NAME_1}
    ports:
      - ${ZOOKEEPER_PORT_1}:${ZOOKEEPER_PORT}
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    environment:
      - ZOO_MY_ID=${ZOOKEEPER_ID_1}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
      - TZ=${TZ}
    networks:
      - kafka-standalone-network

  #zookeeper可视化
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    hostname: zoonavigator
    ports:
      - "9110:9000"
    environment:
      - HTTP_PORT=9000
      - CONNECTION_MYZK_CONN=${KAFKA_ZOOKEEPER_CONNECT}
      - AUTO_CONNECT_CONNECTION_ID=MYZK
    depends_on:
      - ${ZOOKEEPER_NAME_1}
    networks:
      - zookeeper-standalone-network