version: '3.8'

networks:
  mongodb-standalone-network:
    driver: bridge

services:
  mongodb:
    build: ./mongodb
    hostname: mongodb
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    networks:
      - mongodb-standalone-network

  mongodb-webui:
    build:
      context: ./mongo-webui
    hostname: mongodb-webui
    container_name: mongodb-webui
    environment:
      - ROOT_URL=${MONGO_WEBUI_ROOT_URL}
      - MONGO_URL=${MONGO_WEBUI_MONGO_URL}
      - INSTALL_MONGO=${MONGO_WEBUI_INSTALL_MONGO}
    volumes:
      - ${DATA_PATH_HOST}/mongo-webui:/data/db
    ports:
      - "${MONGO_WEBUI_PORT}:3000"
    networks:
      - mongodb-standalone-network
    depends_on:
      - mongodb
