version: '3.8'

volumes:
  jenkins:
    driver: ${VOLUMES_DRIVER}

services:

### Jenkins ################################################
  jenkins:
    build:
      context: ${JENKINS_HOST_PATH}
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
      - TZ=${TZ}
    container_name: ${JENKINS_CONTAINER_NAME}
    hostname: ${JENKINS_HOSTNAME}
    privileged: true
    ports:
      - "${JENKINS_HOST_SLAVE_AGENT_PORT}:50000"
      - "${JENKINS_HOST_HTTP_PORT}:8080"
    volumes:
      - ${DOCKER_SOCK_PATH_HOST}:/var/run/docker.sock
      - ${DATA_PATH_HOST}/jenkins/jenkins_home:/var/jenkins_home
    networks:
      frontend:
        ipv4_address: ${JENKINS_FRONTEND_IP}
      backend:
        ipv4_address: ${JENKINS_BACKEND_IP}