version: "3.8"

include:
  - ../_common/docker-compose-common.yml
  - ./docker-compose-gitlab.yml
  - ./docker-compose-jenkins.yml
  - ./docker-compose-application.yml
  # - ./docker-compose-gitlab-runner.yml