version: '3.8'

volumes:
  hello:
    driver: ${VOLUMES_DRIVER}

services:

### Go Application ################################################
  hello:
    build:
      context: ${APPLICATION_HOST_PATH}
      args:
        - APPLICATION_VERSION=${APPLICATION_VERSION}
        - GO_VERSION=${APPLICATION_GO_VERSION}
        - APPLICATION_CODE_PATH_HOST=${APPLICATION_CODE_PATH_HOST}
        - APPLICATION_MAIN_NAME=${APPLICATION_MAIN_NAME}
    container_name: ${APPLICATION_CONTAINER_NAME}
    hostname: ${APPLICATION_HOSTNAME}
    privileged: true
    environment:
      - TZ=${TZ}
    ports:
      - "${APPLICATION_HOST_HTTP_PORT}:12000"
    networks:
      frontend:
        ipv4_address: ${APPLICATION_FRONTEND_IP}
      backend:
        ipv4_address: ${APPLICATION_BACKEND_IP}
