version: '3.8'

networks:
  zookeeper-cluster-network:
    driver: bridge

services:
  zookeeper2:
    image: zookeeper:${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_NAME_2}
    hostname: ${ZOOKEEPER_NAME_2}
    ports:
      - ${ZOOKEEPER_PORT_2}:${ZOOKEEPER_PORT}
    environment:
      - ZOO_MY_ID=${ZOOKEEPER_ID_2}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
      - TZ=${TZ}
    volumes:
      - ./zookeeper2/data:/data
      - ./zookeeper2/datalog:/datalog
    networks:
      - zookeeper-cluster-network

  zookeeper3:
    image: zookeeper:${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_NAME_3}
    hostname: ${ZOOKEEPER_NAME_3}
    ports:
      - ${ZOOKEEPER_PORT_3}:${ZOOKEEPER_PORT}
    environment:
      - ZOO_MY_ID=${ZOOKEEPER_ID_3}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
      - TZ=${TZ}
    volumes:
      - ./zookeeper3/data:/data
      - ./zookeeper3/datalog:/datalog
    networks:
      - zookeeper-cluster-network

  zookeeper4:
    image: zookeeper:${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_NAME_4}
    hostname: ${ZOOKEEPER_NAME_4}
    ports:
      - ${ZOOKEEPER_PORT_4}:${ZOOKEEPER_PORT}
    environment:
      - ZOO_MY_ID=${ZOOKEEPER_ID_4}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
      - TZ=${TZ}
    volumes:
      - ./zookeeper4/data:/data
      - ./zookeeper4/datalog:/datalog
    networks:
      - zookeeper-cluster-network
      
      
  #zookeeper可视化
  zoonavigator1:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator1
    hostname: zoonavigator1
    ports:
      - "9110:9000"
    environment:
      - HTTP_PORT=9000
      - CONNECTION_MYZK_CONN=${KAFKA_ZOOKEEPER_CONNECT}
      - AUTO_CONNECT_CONNECTION_ID=MYZK
    depends_on:
      - ${ZOOKEEPER_NAME_2}
      - ${ZOOKEEPER_NAME_3}
      - ${ZOOKEEPER_NAME_4}
    networks:
      - zookeeper-cluster-network