version: '3.8'

networks:
  backend:
    external: true

# kraft通用配置
x-kafka-kraft-env: &kafka-kraft-env
  TZ: ${TZ}
  ALLOW_PLAINTEXT_LISTENER: yes
  KAFKA_ENABLE_KRAFT: yes
  KAFKA_KRAFT_CLUSTER_ID: MTIzNDU2Nzg5MGFiY2RlZg
  KAFKA_CFG_PROCESS_ROLES: broker,controller
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_BROKER_ID}@${KAFKA_CONTAINER_NAME}:9091

services:
  kraft-kafka:
    build:
      context: ../kafka
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
    container_name: ${KAFKA_CONTAINER_NAME}
    hostname: ${KAFKA_CONTAINER_NAME}
    privileged: true
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
    environment:
      <<: *kafka-kraft-env
      KAFKA_CFG_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_CFG_LISTENERS: CONTROLLER://:9091,BROKER://:${KAFKA_EXTERNAL_PORT} # 9092内网访问,9093外网访问
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://${PUBLIC_IP}:${KAFKA_EXTERNAL_PORT} #公网ip
    volumes:
      - ${KAFKA_PATH}/data:/bitnami/kafka
    networks:
      backend:
        ipv4_address: ${KRAFT_KAFKA_IP}