version: '3.8'

networks:
  lanp-network:
    external: true

services:
  python-latest:
    build:
      context: ./
    hostname: python-latest
    container_name: python-latest
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
      - TZ=${TZ}
    networks:
      lanp-network:
        ipv4_address: ${PYTHON_STANDALONE_IP}