version: '3.8'

volumes:
  tomcat8:
    driver: ${VOLUMES_DRIVER}

services:

### Tomcat ###############################################
  tomcat8:
    build:
      context: ${TOMCAT8_HOST_PATH}
      args:
        - TOMCAT_VERSION=${TOMCAT8_VERSION}
    container_name: ${TOMCAT8_CONTAINER_NAME}
    hostname: ${TOMCAT8_HOSTNAME}
    privileged: true
    volumes:
      - ${TOMCAT8_WEBAPP_PATH}:/usr/local/tomcat/webapps
      - ${LOG_PATH_HOST}/${TOMCAT8_CONTAINER_NAME}:/usr/local/tomcat/logs
      - ${TOMCAT8_CONF_PATH}:/usr/local/tomcat/conf
    environment:
      - TZ=${TZ}
    ports:
      - "${TOMCAT8_HOST_HTTP_PORT}:8080"
    networks:
      frontend:
        ipv4_address: ${TOMCAT8_FRONTEND_IP}
      backend:
        ipv4_address: ${TOMCAT8_BACKEND_IP}