version: '3.8'

volumes:
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}

services:

### phpMyAdmin ###########################################
  phpmyadmin:
    build: ${PMA_HOST_PATH}
    container_name: ${PMA_CONTAINER_NAME}
    hostname: ${PMA_HOSTNAME}
    privileged: true
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    ports:
      - "${PMA_HOST_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      frontend:
        ipv4_address: ${PMA_FRONTEND_IP}
      backend:
        ipv4_address: ${PMA_BACKEND_IP}