version: '3.8'

volumes:
  redis:
    driver: ${VOLUMES_DRIVER}

services:

### Redis ################################################
  redis:
    build:
      context: ${REDIS_HOST_PATH}
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    hostname: ${REDIS_HOSTNAME}
    container_name: ${REDIS_CONTAINER_NAME}
    command: "--requirepass ${REDIS_PASSWORD}"
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME}:/var/log/redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    environment:
      - TZ=${TZ}
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP}