version: '3.8'

volumes:
  redis-stack:
    driver: ${VOLUMES_DRIVER}

services:

### Redis Stack ##############################################
  redis-stack:
    build:
      context: ${REDIS_STACK_HOST_PATH}
      args:
        - REDIS_STACK_VERSION=${REDIS_STACK_VERSION}
    hostname: ${REDIS_STACK_HOSTNAME}
    container_name: ${REDIS_STACK_CONTAINER_NAME}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/redis-stack/data:/data
      - ${LOG_PATH_HOST}/redis-stack:/var/log/redis
      - ${REDIS_STACK_HOST_PATH}/redis-stack.conf:/redis-stack.conf
    ports:
      - "${REDIS_STACK_HOST_PORT}:6379"
      - "${REDIS_STACK_INSIGHT_PORT}:8001"
    environment:
      - TZ=${TZ}
    networks:
      frontend:
        ipv4_address: ${REDIS_STACK_FRONTEND_IP}
      backend:
        ipv4_address: ${REDIS_STACK_BACKEND_IP}