version: '3.8'

networks:
  tomcat-network:
    driver: bridge

services:
  tomcat:
    build:
      context: ./
    volumes:
      - ./tomcat/holy:/usr/local/tomcat/webapps/holy
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
      - "8088:8088"
      - "8099:8099"
    networks:
      - tomcat-network