version: '3.8'

networks:
  backand:
    external: true

services:
  tomcat:
    build:
      context: ./tomcat
    container_name: tomcat
    hostname: tomcat
    volumes:
      - ${TOMCAT_WEBAPP_PATH}:/usr/local/tomcat/webapps
    environment:
      - TZ=${TZ}
    ports:
      - "8080:8080"
      - "8088:8088"
      - "8099:8099"
    networks:
      backand:
        ipv4_address: ${TOMCAT_IP}