version: '3.8'

networks:
  zznetwork:
    name: zznetwork
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${SUBNET_GATEWAY}

services:
  setup: # empty container 用来创建网络
    build:
      context: ./scratch/scratch
    container_name: setup
    hostname: setup
    networks:
      zznetwork:
        ipv4_address: ${SETUP_IP}