version: "3.8"

include:
  - ./_compose/docker-compose-common.yml
  - ./_compose/docker-compose-network.yml
  - ./_compose/docker-compose-busybox.yml
  - ./_compose/docker-compose-portainer.yml
  - ./_compose/docker-compose-gitlab.yml
  - ./_compose/docker-compose-jenkins.yml
  - ./_compose/docker-compose-mysql57.yml
  - ./_compose/docker-compose-mysql.yml
  - ./_compose/docker-compose-redis.yml
  - ./_compose/docker-compose-redis-stack.yml




### OpenResty Server #####################################
### ElasticSearch ########################################
### Logstash #############################################
### Kibana ###############################################
### Grafana ##############################################
### IPython ##############################################
### JupyterHub ###########################################
### Metabase #############################################
### DOCKER-REGISTRY ######################################
### DOCKER-WEB-UI ########################################
### SONARQUBE ############################################
### kafka ################################################
### kafka-manager ########################################
### keycloak #############################################
### tarantool ###########################################
### REDISWEBUI ###########################################
### MongoWebUI ###########################################