version: '3.8'

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${SUBNET_GATEWAY}

#volumes:
#  redis:
#    driver: local

services:
# empty container 用来创建网络
  empty:
    build:
      context: ./scratch/scratch
    container_name: empty
    networks:
      - backend