version: '3.8'

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${SUBNET_GATEWAY}

#volumes:
#  redis:
#    driver: local

services:
# empty container 用来创建网络
  container-env-setup:
    build:
      context: ./scratch/scratch
    container_name: container-env-setup
    hostname: container-env-setup
    networks:
      backend:
        ipv4_address: ${CONTAINER_ENV_SETUP_IP}