version: "3.8"

networks:
  backend:
    external: true

services:
  canal-admin:
    build:
      context: ./canal-admin
      args:
        CANAL_VERSION: ${CANAL_VERSION}
    hostname: ${CANAL_ADMIN_CONTAINER_NAME}
    container_name: ${CANAL_ADMIN_CONTAINER_NAME}
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.address=${MYSQL_CONTAINER_NAME}:3306 # 想使用外部mysql就必须通过环境变量配置，实现如此，不必纠结
    volumes:
      - ${CANAL_ADMIN_PATH}/conf/application.yml:/home/admin/canal-admin/conf/application.yml
      - ${CANAL_ADMIN_PATH}/logs:/home/admin/canal-admin/logs
    networks:
      backend:
        ipv4_address: ${CANAL_ADMIN_IP}

  canal-server:
    build:
      context: ./canal-server
      args:
        CANAL_VERSION: ${CANAL_VERSION}
    hostname: ${CANAL_CONTAINER_NAME}
    container_name: ${CANAL_CONTAINER_NAME}
    ports:
      - "11110:11110" # admin
      - "11111:11111" # canal
      - "11112:11112" # metrics
      - "9100:9100"   # exporter
    environment:
      - canal.auto.scan=true
      - canal.destinations=canal_test
    volumes:
      - ${CANAL_PATH}/conf/canal_test/instance.properties:/home/admin/canal-server/conf/canal_test/instance.properties
      - ${CANAL_PATH}/conf/canal_local.properties:/home/admin/canal-server/conf/canal_local.properties
      - ${CANAL_PATH}/logs:/home/admin/canal-server/logs
    networks:
      backend:
        ipv4_address: ${CANAL_IP}