version: '3.8'

volumes:
  apache:
    driver: ${VOLUMES_DRIVER}

services:

### Apache Server ########################################
  apache:
    build:
      context: ${APACHE_HOST_PATH}
      args:
        - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
        - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
        - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
        - APACHE_INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}
        - APACHE_FOR_MAC_M1=${APACHE_FOR_MAC_M1}
    container_name: ${APACHE_CONTAINER_NAME}
    hostname: ${APACHE_HOSTNAME}
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}"
      - "${LOG_PATH_HOST}/lamp/apache:/var/log/apache2"
      - "${APACHE_SITES_PATH}:/etc/apache2/sites-available"
      - "${APACHE_SSL_PATH}:/etc/apache2/ssl"
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
      - "8212:8212"
      - "8222:8222"
      - "8211:8211"
      - "8213:8213"
      - "8223:8223"
      - "8231:8231"
      - "8224:8224"
      - "8221:8221"
      - "8242:8242"
    depends_on:
      - php-fpm
    networks:
      frontend:
        ipv4_address: ${APACHE_FRONTEND_IP}
      backend:
        ipv4_address: ${APACHE_BACKEND_IP}