version: "3.8"

volumes:
  sentinel1:
    driver: ${VOLUMES_DRIVER}
  sentinel2:
    driver: ${VOLUMES_DRIVER}
  sentinel3:
    driver: ${VOLUMES_DRIVER}

x-build: &build
  build:
    context: ${REDIS_HOST_PATH}
    args:
      REDIS_VERSION: ${REDIS_VERSION}

services:

### SENTINEL NODE1 ##############################################
  sentinel1:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_SENTINEL1}
    hostname: ${REDIS_HOSTNAME_SENTINEL1}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_SENTINEL1}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_SENTINEL1}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_SENTINEL1}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_SENTINEL1}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_SENTINEL1}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_SENTINEL1}

### SENTINEL NODE2 ##############################################
  sentinel2:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_SENTINEL2}
    hostname: ${REDIS_HOSTNAME_SENTINEL2}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_SENTINEL2}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_SENTINEL2}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_SENTINEL2}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_NODE2}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_SENTINEL2}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_SENTINEL2}

### SENTINEL NODE3 ##############################################
  sentinel3:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_SENTINEL3}
    hostname: ${REDIS_HOSTNAME_SENTINEL3}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_SENTINEL3}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_SENTINEL3}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_SENTINEL3}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_SENTINEL3}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_SENTINEL3}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_SENTINEL3}