version: "3.8"

volumes:
  redis1:
    driver: ${VOLUMES_DRIVER}
  redis2:
    driver: ${VOLUMES_DRIVER}
  redis3:
    driver: ${VOLUMES_DRIVER}
  redis4:
    driver: ${VOLUMES_DRIVER}

x-build: &build
  build:
    context: ${REDIS_HOST_PATH}
    args:
      REDIS_VERSION: ${REDIS_VERSION}

services:

### REDIS NODE1 ##############################################
  redis1:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE1}
    hostname: ${REDIS_HOSTNAME_NODE1}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_NODE1}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE1}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE1}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_NODE1}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_NODE1}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE1}

### REDIS NODE2 ##############################################
  redis2:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE2}
    hostname: ${REDIS_HOSTNAME_NODE2}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_NODE2} ${REDIS_REPLICAOF}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE2}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE2}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_NODE2}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_NODE2}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE2}

### REDIS NODE3 ##############################################
  redis3:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE3}
    hostname: ${REDIS_HOSTNAME_NODE3}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_NODE3} ${REDIS_REPLICAOF}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE3}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE3}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_NODE3}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_NODE3}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE3}

### REDIS NODE4 ##############################################
  redis4:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE4}
    hostname: ${REDIS_HOSTNAME_NODE4}
    privileged: true
    environment:
      - REDIS_ARGS="${REDIS_COMMON_ARGS} --slave-announce-port ${REDIS_HOST_PORT_NODE4} ${REDIS_REPLICAOF}"
    volumes:
      - "${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE4}/data:/data"
      - "${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE4}:/var/log/redis"
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT_NODE4}:6379"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP_NODE4}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE4}