version: '3.8'

networks:
  backend:
    external: true

services:
  zookeeper:
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_NAME}
    hostname: ${ZOOKEEPER_NAME}
    ports:
      - "2181:2181"
    volumes:
      - ${ZOOKEEPER_PATH}/data:/data
      - ${ZOOKEEPER_PATH}/datalog:/datalog
    environment:
      - TZ=${TZ}
      - ZOO_MY_ID=${ZOOKEEPER_ID}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
      - ZOO_4LW_COMMANDS_WHITELIST=\* #stat,conf,envi
    networks:
      backend:
        ipv4_address: ${ZOOKEEPER_IP}