version: '3.8'

networks:
  backend:
    external: true

services:
  zookeeper:
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_NAME}
    hostname: ${ZOOKEEPER_NAME}
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - ${ZOOKEEPER_DATA_PATH}:/data
      - ${ZOOKEEPER_DATALOG_PATH}:/datalog
    environment:
      - ZOO_MY_ID=${ZOOKEEPER_ID}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
      - TZ=${TZ}
    networks:
      backend:
        ipv4_address: ${ZOOKEEPER_IP}