version: '3.8'

networks:
  backend:
    external: true

x-memcached-env: &memcached-env
  TZ: ${TZ}

x-memcached-build: &memcached-build
  build:
    context: ./memcached
    args:
      MEMCACHED_VERSION: ${MEMCACHED_VERSION}

services:
  memcached1:
    <<: *memcached-build
    hostname: ${MEMCACHED_1_CONTAINER_NAME}
    container_name: ${MEMCACHED_1_CONTAINER_NAME}
    ports:
      - "${MEMCACHED_1_HOST_PORT}:11211"
    environment:
      <<: *memcached-env
    volumes:
      - ${MEMCACHED_1_PATH}/data:/var/lib/memcached
    networks:
      backend:
        ipv4_address: ${MEMCACHED_1_IP}

  memcached2:
    <<: *memcached-build
    hostname: ${MEMCACHED_2_CONTAINER_NAME}
    container_name: ${MEMCACHED_2_CONTAINER_NAME}
    ports:
      - "${MEMCACHED_2_HOST_PORT}:11211"
    environment:
      <<: *memcached-env
    volumes:
      - ${MEMCACHED_2_PATH}/data:/var/lib/memcached
    networks:
      backend:
        ipv4_address: ${MEMCACHED_2_IP}

  memcached3:
    <<: *memcached-build
    hostname: ${MEMCACHED_3_CONTAINER_NAME}
    container_name: ${MEMCACHED_3_CONTAINER_NAME}
    ports:
      - "${MEMCACHED_3_HOST_PORT}:11211"
    environment:
      <<: *memcached-env
    volumes:
      - ${MEMCACHED_3_PATH}/data:/var/lib/memcached
    networks:
      backend:
        ipv4_address: ${MEMCACHED_3_IP}