version: "3.8"

networks:
  backend:
    external: true

services:
  hello:
    build:
      context: .
    hostname: hello-v3
    container_name: hello-v3
    ports:
      - "8080:8080"
    networks:
      backend:
        ipv4_address: 172.19.200.14
