version: '3.8'

networks:
  backend:
    external: true

services:
  caddy:
    build:
      context: ./caddy
    hostname: caddy
    container_name: caddy
    volumes:
      - ./www/:/var/www:cached
      - ${CADDY_ETC_PATH}:/etc/caddy
      - ${CADDY_CONFIG_PATH}:/config
      - ${CADDY_LOG_PATH}:/var/log/caddy
      - ${CADDY_DATA_PATH}:/root/.caddy
      - ${CADDY_SSL_PATH}:/root/ssl
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    environment:
      - TZ=${TZ}
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP}
    networks:
      backend:
        ipv4_address: ${CADDY_IP}