version: '3.8'

networks:
  beanstalkd-standalone-network:
    driver: bridge

services:
  beanstalkd:
    build:
      context: ./beanstalkd
    hostname: beanstalkd
    container_name: beanstalkd
    ports:
      - ${BEANSTALKD_HOST_PORT}:11300
    volumes:
      - ./beanstalkd/data:/var/lib/beanstalkd
    privileged: true
    environment:
      - TZ=${TZ}
    networks:
      beanstalkd-standalone-network:

  beanstalkd-console:
    build:
      context: ./beanstalkd-console
    hostname: beanstalkd-console
    container_name: beanstalkd-console
    ports:
      - ${BEANSTALKD_CONSOLE_HOST_PORT}:2080
    environment:
      - TZ=${TZ}
      - BEANSTALK_SERVERS=beanstalkd:${BEANSTALKD_HOST_PORT}
    depends_on:
      - beanstalkd
    networks:
      beanstalkd-standalone-network: