version: '3.8'

networks:
  backend:
    external: true

services:
  rocketmq-namesrv:
    build:
      context: ./namesrv
      args:
        ROCKETMQ_VERSION: ${ROCKETMQ_VERSION}
    hostname: ${NAMESRV_CONTAINER_NAME}
    container_name: ${NAMESRV_CONTAINER_NAME}
    ports:
      - "${NAMESRV_PORT}:9876"
    environment:
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m -Xmn128m
    volumes:
      - ${NAMESRV_PATH}/logs:/home/rocketmq/logs
    networks:
      backend:
        ipv4_address: ${ROCKETMQ_NAMESRV_IP}

  rocketmq-broker:
    build:
      context: ./broker
      args:
        ROCKETMQ_VERSION: ${ROCKETMQ_VERSION}
    hostname: ${ROCKETMQ_BROKER_CONTAINER_NAME}
    container_name: ${ROCKETMQ_BROKER_CONTAINER_NAME}
    volumes:
      - ${ROCKETMQ_BROKER_PATH}/logs:/home/rocketmq/logs
      - ${ROCKETMQ_BROKER_PATH}/store:/home/rocketmq/store
      - ${ROCKETMQ_BROKER_PATH}/conf/broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    environment:
      - NAMESRV_ADDR=${NAMESRV_CONTAINER_NAME}:9876
      - JAVA_OPTS= -Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m -Xmn200m
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    depends_on:
      - ${NAMESRV_CONTAINER_NAME}
    networks:
      backend:
        ipv4_address: ${ROCKETMQ_BROKER_IP}

  rocketmq-dashboard:
    build:
      context: ./dashboard
    hostname: rocketmq-dashboard
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=${NAMESRV_CONTAINER_NAME}:9876; -Xms256m -Xmx256m
    depends_on:
      - ${NAMESRV_CONTAINER_NAME}
    networks:
      backend:
        ipv4_address: ${ROCKETMQ_DASHBOARD_IP}