version: '3.8'

networks:
  backend:
    driver: bridge

services:
  rocketmq-nameserver:
    build:
      context: ./nameserver
      args:
        ROCKETMQ_IMAGE: ${ROCKETMQ_IMAGE}
        ROCKETMQ_VERSION: ${ROCKETMQ_VERSION}
    hostname: rocketmq-nameserver
    container_name: rocketmq-nameserver
    ports:
      - ${NAMESRV_PORT}:${NAMESRV_PORT}
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m -Xmn128m
      - TZ=${TZ}
    volumes:
      - ./nameserver/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      backend:
        ipv4_address: ${ROCKETMQ_BROKER_IP}

  rocketmq-broker:
    build:
      context: ./broker
      args:
        ROCKETMQ_IMAGE: ${ROCKETMQ_IMAGE}
        ROCKETMQ_VERSION: ${ROCKETMQ_VERSION}
    hostname: rocketmq-broker
    container_name: rocketmq-broker
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker/conf/broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    environment:
      - NAMESRV_ADDR=${NAMESRV_ADDR}
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m -Xmn128m
      - TZ=${TZ}
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    command: sh mqbroker -c /opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    depends_on:
      - rocketmq-nameserver
    networks:
      backend:
        ipv4_address: ${ROCKETMQ_NAMESRV_IP}

  rocketmq-dashboard:
    build:
      context: ./rocketmq-dashboard
    hostname: rocketmq-dashboard
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=${NAMESRV_ADDR}; -Xms256m -Xmx256m
    depends_on:
      - rocketmq-nameserver
    networks:
      backend:
        ipv4_address: ${ROCKETMQ_DASHBOARD_IP}