version: '3.8'

networks:
  backend:
    external: true

services:
  soketi:
    build:
      context: ./soketi
    container_name: soketi
    hostname: soketi
    environment:
      - TZ=${TZ}
    ports:
      - "${SOKETI_PORT}:6001"
      - "${SOKETI_METRICS_SERVER_PORT}:9601"
    networks:
      backend:
        ipv4_address: ${SOKETI_IP}