version: '3.8'

networks:
  lanp-network:
    external: true

services:
  lanp-56-apache2:
    hostname: lanp-56-apache2
    container_name: lanp-56-apache2
    build:
      context: ./apache2
      args:
        - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
        - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
        - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
        - APACHE_INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
      - "8212:8212"
      - "8222:8222"
      - "8211:8211"
      - "8213:8213"
      - "8223:8223"
      - "8231:8231"
      - "8224:8224"
      - "8221:8221"
      - "8242:8242"
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      - ${APACHE_SSL_PATH}:/etc/apache2/ssl
    networks:
      lanp-network:
        ipv4_address: ${LANP_56_APACHE2_IP}

  lanp-56-mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    hostname: lanp-56-mysql
    container_name: lanp-56-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    networks:
      lanp-network:
        ipv4_address: ${LANP_56_MYSQL_IP}

  lanp-56-redis:
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    hostname: lanp-56-redis
    container_name: lanp-56-redis
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/var/log/redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      lanp-network:
        ipv4_address: ${LANP_56_REDIS_IP}