version: '3.8'

volumes:
  docker-registry:
    driver: ${VOLUMES_DRIVER}
  docker-web-ui:
    driver: ${VOLUMES_DRIVER}

services:

### DOCKER-REGISTRY ########################################
  docker-registry:
    build:
      context: ../docker-registry
    container_name: ${DOCKER_REGISTRY_CONTAINER_NAME}
    hostname: ${DOCKER_REGISTRY_HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_PATH_HOST}/docker-registry:/var/lib/registry
    ports:
      - "${DOCKER_REGISTRY_HOST_PORT}:5000"
    networks:
      frontend:
        ipv4_address: ${DOCKER_REGISTRY_FRONTEND_IP}
      backend:
        ipv4_address: ${DOCKER_REGISTRY_BACKEND_IP}

### DOCKER-WEB-UI ################################################
  docker-web-ui:
    build:
      context: ../docker-web-ui
    container_name: ${DOCKER_WEBUI_CONTAINER_NAME}
    hostname: ${DOCKER_WEBUI_HOSTNAME}
    environment:
      - TZ=${TZ}
      - ENV_DOCKER_REGISTRY_HOST=${DOCKER_WEBUI_REGISTRY_HOST}
      - ENV_DOCKER_REGISTRY_PORT=${DOCKER_WEBUI_REGISTRY_PORT}
      - ENV_DOCKER_REGISTRY_USE_SSL=${DOCKER_REGISTRY_USE_SSL}
      - ENV_MODE_BROWSE_ONLY=${DOCKER_REGISTRY_BROWSE_ONLY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${DOCKER_WEBUI_HOST_PORT}:80"
    networks:
      frontend:
        ipv4_address: ${DOCKER_WEBUI_FRONTEND_IP}
      backend:
        ipv4_address: ${DOCKER_WEBUI_BACKEND_IP}