version: '3.8'

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

### PostgreSQL ###########################################
  postgres:
    build:
      context: ../postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_HOSTNAME}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GITLAB_POSTGRES_INIT=${GITLAB_POSTGRES_INIT}
      - GITLAB_POSTGRES_USER=${GITLAB_POSTGRES_USER}
      - GITLAB_POSTGRES_PASSWORD=${GITLAB_POSTGRES_PASSWORD}
      - GITLAB_POSTGRES_DB=${GITLAB_POSTGRES_DB}
      - KEYCLOAK_POSTGRES_INIT=${KEYCLOAK_POSTGRES_INIT}
      - KEYCLOAK_POSTGRES_USER=${KEYCLOAK_POSTGRES_USER}
      - KEYCLOAK_POSTGRES_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
      - KEYCLOAK_POSTGRES_DB=${KEYCLOAK_POSTGRES_DB}
      - JUPYTERHUB_POSTGRES_INIT=${JUPYTERHUB_POSTGRES_INIT}
      - JUPYTERHUB_POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}
      - JUPYTERHUB_POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}
      - JUPYTERHUB_POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}
      - SONARQUBE_POSTGRES_INIT=${SONARQUBE_POSTGRES_INIT}
      - SONARQUBE_POSTGRES_DB=${SONARQUBE_POSTGRES_DB}
      - SONARQUBE_POSTGRES_USER=${SONARQUBE_POSTGRES_USER}
      - SONARQUBE_POSTGRES_PASSWORD=${SONARQUBE_POSTGRES_PASSWORD}
      - POSTGRES_CONFLUENCE_INIT=${CONFLUENCE_POSTGRES_INIT}
      - POSTGRES_CONFLUENCE_DB=${CONFLUENCE_POSTGRES_DB}
      - POSTGRES_CONFLUENCE_USER=${CONFLUENCE_POSTGRES_USER}
      - POSTGRES_CONFLUENCE_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/postgres/data:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      frontend:
        ipv4_address: ${POSTGRES_FRONTEND_IP}
      backend:
        ipv4_address: ${POSTGRES_BACKEND_IP}