# Author: Al-assad
# Email: yulinying_1994@outlook.com
# Date: 2020-11-27
# Description: docker compose for clickhouse cluster with 3 shards and 1 replica, 3 zookeeper node

version: '2.1'

services:

  zk1:
    image: zookeeper:3.6
    hostname: zk1
    container_name: clickhouse-zookeeper-zk1
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.2
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

  zk2:
    image: zookeeper:3.6
    hostname: zk2
    container_name: clickhouse-zookeeper-zk2
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.3
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

  zk3:
    image: zookeeper:3.6
    hostname: zk3
    container_name: clickhouse-zookeeper-zk3
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.4
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

  clickhouse1:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8124:8123"
    hostname: ch01
    container_name: clickhouse-server-ch01
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.5
    extra_hosts:
      - "zk1:172.18.1.2"
      - "zk2:172.18.1.3"
      - "zk3:172.18.1.4"
      - "ch02:172.18.1.6"
      - "ch03:172.18.1.7"
    volumes:
      - ./ch-conf_3zk-3shard-3replica/metrika_ch01.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

  clickhouse2:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8125:8123"
    hostname: ch02
    container_name: clickhouse-server-ch02
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.6
    extra_hosts:
      - "zk1:172.18.1.2"
      - "zk2:172.18.1.3"
      - "zk3:172.18.1.4"
      - "ch01:172.18.1.5"
      - "ch03:172.18.1.7"
    volumes:
      - ./ch-conf_3zk-3shard-3replica/metrika_ch02.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

  clickhouse3:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8126:8123"
    hostname: ch03
    container_name: clickhouse-server-ch03
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      clickhouse-cluster:
        ipv4_address: 172.18.1.7
    extra_hosts:
      - "zk1:172.18.1.2"
      - "zk2:172.18.1.3"
      - "zk3:172.18.1.4"
      - "ch01:172.18.1.5"
      - "ch02:172.18.1.6"
    volumes:
      - ./ch-conf_3zk-3shard-3replica/metrika_ch03.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

networks:
  clickhouse-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/16
