version: "3.8"

networks:
  lanp-network:
    external: true

services:
  jenkins:
    build:
      context: ./dockerfile
    container_name: ${JENKINS_NAME}
    hostname: ${JENKINS_NAME}
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      lanp-network:
        ipv4_address: ${JENKINS_IP}