version: "3.8"

networks:
  backend:
    external: true

services:
  redismod:
    build:
      context: ./redismod
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: redismod
    hostname: redismod
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
    networks:
      backend:
        ipv4_address: ${REDIS_MOD_IP}
