version: '3.8'

networks:
  nsq-standalone-network:
    driver: bridge

services:
  nsqlookupd1:
    image: nsqio/nsq:latest
    container_name: nsqlookupd1
    hostname: nsqlookupd1
    command: ${NSQ_LOOKUP_COMMAND_1}
    ports:
      - ${NSQ_LOOKUP_TCP_PORT_1}:${NSQ_LOOKUP_TCP_PORT_1}
      - ${NSQ_LOOKUP_HTTP_PORT_1}:${NSQ_LOOKUP_HTTP_PORT_1}
    environment:
      - TZ=${TZ}
    networks:
      nsq-standalone-network:

  nsq1:
    image: nsqio/nsq:latest
    container_name: nsq1
    hostname: nsq1
    command: ${NSQ_COMMAND_1}
    volumes:
      - ./nsq1/data/:/usr/local/nsq/bin/data
    ports:
      - ${NSQ_TCP_PORT_1}:${NSQ_TCP_PORT_1}
      - ${NSQ_HTTP_PORT_1}:${NSQ_HTTP_PORT_1}
    environment:
      - TZ=${TZ}
    depends_on:
      - nsqlookupd1
    networks:
      nsq-standalone-network:

  nsqadmin:
    image: nsqio/nsq:latest
    container_name: nsqadmin
    hostname: nsqadmin
    command: ${NSQ_ADMIN_COMMAND}
    ports:
      - ${NSQ_ADMIN_HTTP_PORT}:${NSQ_ADMIN_HTTP_PORT}
    environment:
      - TZ=${TZ}
    networks:
      nsq-standalone-network:
    depends_on:
      - nsqlookupd1