---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.port: 5601
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch-v7:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials

elasticsearch.username: elastic
elasticsearch.password: changeme
i18n.locale: "zh-CN"
xpack.reporting.encryptionKey: "a_random_string"
xpack.security.encryptionKey: "something_at_least_32_characters"
xpack.encryptedSavedObjects.encryptionKey: "fhjskloppd678ehkdfdlliverpoolfcr"