version: "3.8"

networks:
  backend:
    external: true

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=${ELK_VERSION}
    container_name: ${ELASTICSEARCH_HOSTNAME}
    hostname: ${ELASTICSEARCH_HOSTNAME}
    volumes:
      - ${ELASTICSEARCH_PATH}/data:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_PATH}/plugins:/usr/share/elasticsearch/plugins
    environment:
      - TZ=${TZ}
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - node.name=${ELASTICSEARCH_HOSTNAME}
      - cluster.name=${ELASTICSEARCH_HOSTNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-credentials=true
      - http.cors.allow-headers="X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      backend:
        ipv4_address: ${ELASTICSEARCH_IP}

  kibana:
    build:
      context: ./kibana
      args:
        - ELK_VERSION=${ELK_VERSION}
    container_name: ${KIBANA_HOSTNAME}
    hostname: ${KIBANA_HOSTNAME}
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    volumes:
      - ${KIBANA_PATH}/data:/usr/share/kibana/data
    environment:
      - TZ=${TZ}
      - I18N_LOCALE="zh-CN"
    networks:
      backend:
        ipv4_address: ${KIBANA_IP}