version: '3.8'

networks:
  esv7-standalone-network:
    driver: bridge

services:
  elasticsearchV7:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearchV7
    hostname: elasticsearchV7
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: ./elasticsearch/data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
#      - node.name=es01
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - esv7-standalone-network

  logstashV7:
    build:
      context: ./logstash
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstashV7
    hostname: logstashV7
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - esv7-standalone-network
    depends_on:
      - elasticsearchV7

  kibanaV7:
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibanaV7
    hostname: kibanaV7
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - esv7-standalone-network
    depends_on:
      - elasticsearchV7

  filebeatV7:
    build:
      context: ./filebeat
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeatV7
    hostname: filebeatV7
    privileged: true
    user: root # 必须为root
    environment:
      - strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # 映射到容器中[作为数据源]
      - ./filebeat/logs:/usr/share/filebeat/logs:rw
      - ./filebeat/data:/usr/share/filebeat/data:rw
    networks:
      - esv7-standalone-network
    depends_on:
      - elasticsearchV7
      - logstashV7