version: '3.8'

networks:
  backend:
    external: true

services:
  beanstalkd:
    build:
      context: ./beanstalkd
    hostname: beanstalkd
    container_name: beanstalkd
    ports:
      - "${BEANSTALKD_HOST_PORT}:11300"
    volumes:
      - ${BEANSTALKD_DATA_PATH}:/var/lib/beanstalkd
    environment:
      - TZ=${TZ}
    networks:
      backend:
        ipv4_address: ${BEANSTALKD_IP}

  beanstalkd-console:
    build:
      context: ./beanstalkd-console
    hostname: beanstalkd-console
    container_name: beanstalkd-console
    ports:
      - "${BEANSTALKD_CONSOLE_HOST_PORT}:2080"
    environment:
      - TZ=${TZ}
      - BEANSTALK_SERVERS=beanstalkd:${BEANSTALKD_HOST_PORT}
    depends_on:
      - beanstalkd
    networks:
      backend:
        ipv4_address: ${BEANSTALKD_CONSOLE_IP}