version: '3.8'

networks:
  rabbitmq-standalone-network:
    driver: bridge

services:
  rabbitmq:
    build:
      context: ./
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_NODE_HOST_PORT_1}:${RABBITMQ_NODE_HOST_PORT}
      - ${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT_1}:${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=${RABBITMQ_NODENAME_1}
      - TZ=${TZ}
    volumes:
      - ./rabbitmq/etc/rabbitmq:/etc/rabbitmq
    networks:
      rabbitmq-standalone-network: