version: '3.8'

networks:
  backand:
    external: true

services:
  nginx:
    build:
      context: ./nginx
    hostname: nginx
    container_name: nginx
    environment:
      - TZ=${TZ}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ./www/:/var/www:cached
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    networks:
      backand:
        ipv4_address: ${NGINX_IP}