version: '3.8'

networks:
  pulsar-standalone-network:
    driver: bridge

services:
  pulsar:
    image: apachepulsar/pulsar:${PULSAR_VERSION}
    hostname: pulsar
    container_name: pulsar
    volumes:
      - ./pulsar/data:/pulsar/data
    ports:
      - "6650:6650"
      - "8095:8080"
    environment:
      - TZ=${TZ}
    command: bin/pulsar standalone
    networks:
      pulsar-standalone-network:

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.2.0
    hostname: pulsar-manager
    container_name: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
      - TZ=${TZ}
    networks:
      pulsar-standalone-network:
    depends_on:
      - pulsar

