version: '3.8'

networks:
  backend:
    external: true

x-redis-env: &redis-env
  TZ: ${TZ}

x-redis-build: &redis-build
  build:
    context: ./redis
    args:
      REDIS_VERSION: ${REDIS_VERSION}

services:
  redis-master1:
    <<: *redis-build
    container_name: ${REDIS_MASTER_1_CONTAINER_NAME}
    hostname: ${REDIS_MASTER_1_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_MASTER_1_PORT}:6379"
    volumes:
      - ${REDIS_MASTER_1_PATH}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_MASTER_1_PATH}/data:/data
      - ${REDIS_MASTER_1_PATH}/logs:/var/log/redis
    networks:
      backend:
        ipv4_address: ${REDIS_MASTER_1_IP}

  redis-slave1:
    <<: *redis-build
    container_name: ${REDIS_SLAVE_1_CONTAINER_NAME}
    hostname: ${REDIS_SLAVE_1_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_SLAVE_1_PORT}:6379"
    volumes:
      - ${REDIS_SLAVE_1_PATH}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_SLAVE_1_PATH}/data:/data
      - ${REDIS_SLAVE_1_PATH}/logs:/var/log/redis
    networks:
      backend:
        ipv4_address: ${REDIS_SLAVE_1_IP}

  redis-slave2:
    <<: *redis-build
    container_name: ${REDIS_SLAVE_2_CONTAINER_NAME}
    hostname: ${REDIS_SLAVE_2_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_SLAVE_2_PORT}:6379"
    volumes:
      - ${REDIS_SLAVE_2_PATH}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_SLAVE_2_PATH}/data:/data
      - ${REDIS_SLAVE_2_PATH}/logs:/var/log/redis
    networks:
      backend:
        ipv4_address: ${REDIS_SLAVE_2_IP}

  redis-slave3:
    <<: *redis-build
    container_name: ${REDIS_SLAVE_3_CONTAINER_NAME}
    hostname: ${REDIS_SLAVE_3_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_SLAVE_3_PORT}:6379"
    volumes:
      - ${REDIS_SLAVE_3_PATH}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_SLAVE_3_PATH}/data:/data
      - ${REDIS_SLAVE_3_PATH}/logs:/var/log/redis
    networks:
      backend:
        ipv4_address: ${REDIS_SLAVE_3_IP}

  redis-sentinel1:
    <<: *redis-build
    container_name: ${REDIS_SENTINEL_1_CONTAINER_NAME}
    hostname:  ${REDIS_SENTINEL_1_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_SENTINEL_1_PORT}:26379"
    volumes:
      - ${REDIS_SENTINEL_1_PATH}/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      backend:
        ipv4_address: ${REDIS_SENTINEL_1_IP}

  redis-sentinel2:
    <<: *redis-build
    container_name: ${REDIS_SENTINEL_2_CONTAINER_NAME}
    hostname: ${REDIS_SENTINEL_2_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_SENTINEL_2_PORT}:26379"
    volumes:
      - ${REDIS_SENTINEL_2_PATH}/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      backend:
        ipv4_address: ${REDIS_SENTINEL_2_IP}

  redis-sentinel3:
    <<: *redis-build
    container_name: ${REDIS_SENTINEL_3_CONTAINER_NAME}
    hostname: ${REDIS_SENTINEL_3_CONTAINER_NAME}
    environment:
      <<: *redis-env
    ports:
      - "${REDIS_SENTINEL_3_PORT}:26379"
    volumes:
      - ${REDIS_SENTINEL_3_PATH}/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      backend:
        ipv4_address: ${REDIS_SENTINEL_3_IP}