version: '3.8'

networks:
  zznetwork:
    external: true

services:
  busybox:
    build:
      context: ./busybox
      args:
        - BUSYBOX_VERSION=${BUSYBOX_VERSION}
    container_name: busybox
    hostname: busybox
    privileged: true
    stdin_open: true
    tty: true
    networks:
      zznetwork:
        ipv4_address: ${BUSYBOX_IP}