version: "3.8"

networks:
  redis-standalone-network:
    driver: bridge

services:
  redis:
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: redis
    hostname: redis
    environment:
      - TZ=${TZ}
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
    networks:
      redis-standalone-network:
