version: "3.8"

networks:
  lanp-network:
    external: true

services:
  redis:
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: redis
    hostname: redis
    environment:
      - TZ=${TZ}
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
    networks:
      lanp-network:
        ipv4_address: ${REDIS_IP}
