version: "3.8"

networks:
  backend:
    external: true

services:
  redis:
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: redis
    hostname: redis
    environment:
      - TZ=${TZ}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
    networks:
      backend:
        ipv4_address: ${REDIS_IP}
