version: '3.8'

networks:
  yapi-network:
    driver: bridge

services:
  yapi:
    build:
      context: ./yapi
    ports:
      - "${YAPI_HOST_HTTP_PORT}:3000"
    depends_on:
      - mongo
    tty: true
    networks:
      - yapi-network