version: '3.8'

networks:
  lanp-network:
    external: true

services:
  memcached1:
    build:
      context: ./dockerfile
    hostname: memcached1
    container_name: memcached1
    ports:
      - "${MEMCACHED_HOST_PORT_1}:11211"
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ./memcached1:/var/lib/memcached
    networks:
      lanp-network:
        ipv4_address: ${MEMCACHED_1_IP}

  memcached2:
    build:
      context: ./dockerfile
    hostname: memcached2
    container_name: memcached2
    ports:
      - "${MEMCACHED_HOST_PORT_2}:11211"
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ./memcached2:/var/lib/memcached
    networks:
      lanp-network:
        ipv4_address: ${MEMCACHED_2_IP}

  memcached3:
    build:
      context: ./dockerfile
    hostname: memcached3
    container_name: memcached3
    ports:
      - "${MEMCACHED_HOST_PORT_3}:11211"
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ./memcached3:/var/lib/memcached
    networks:
      lanp-network:
        ipv4_address: ${MEMCACHED_3_IP}