version: '3.8'

networks:
  backend:
    external: true

services:
  redis1:
    build:
      context: ./redis-cluster
      args:
        REDIS_CLUSTER_VERSION: ${REDIS_CLUSTER_VERSION}
    container_name: ${REDIS_1_CONTAINER_NAME}
    hostname: ${REDIS_1_CONTAINER_NAME}
    volumes:
      - ${REDIS_1_PATH}/data:/bitnami/redis/data
    ports:
      - "${REDIS_1_PORT}:6379"
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=${REDIS_NODES}
    networks:
      backend:
        ipv4_address: ${REDIS_1_IP}

  redis2:
    build:
      context: ./redis-cluster
      args:
        REDIS_CLUSTER_VERSION: ${REDIS_CLUSTER_VERSION}
    container_name: ${REDIS_2_CONTAINER_NAME}
    hostname: ${REDIS_2_CONTAINER_NAME}
    volumes:
      - ${REDIS_2_PATH}/data:/bitnami/redis/data
    ports:
      - "${REDIS_2_PORT}:6379"
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=${REDIS_NODES}
    networks:
      backend:
        ipv4_address: ${REDIS_2_IP}

  redis3:
    build:
      context: ./redis-cluster
      args:
        REDIS_CLUSTER_VERSION: ${REDIS_CLUSTER_VERSION}
    container_name: ${REDIS_3_CONTAINER_NAME}
    hostname: ${REDIS_3_CONTAINER_NAME}
    volumes:
      - ${REDIS_3_PATH}/data:/bitnami/redis/data
    ports:
      - "${REDIS_3_PORT}:6379"
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=${REDIS_NODES}
    networks:
      backend:
        ipv4_address: ${REDIS_3_IP}

  redis4:
    build:
      context: ./redis-cluster
      args:
        REDIS_CLUSTER_VERSION: ${REDIS_CLUSTER_VERSION}
    container_name: ${REDIS_4_CONTAINER_NAME}
    hostname: ${REDIS_4_CONTAINER_NAME}
    volumes:
      - ${REDIS_4_PATH}/data:/bitnami/redis/data
    ports:
      - "${REDIS_4_PORT}:6379"
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=${REDIS_NODES}
    networks:
      backend:
        ipv4_address: ${REDIS_4_IP}

  redis5:
    build:
      context: ./redis-cluster
      args:
        REDIS_CLUSTER_VERSION: ${REDIS_CLUSTER_VERSION}
    container_name: ${REDIS_5_CONTAINER_NAME}
    hostname: ${REDIS_5_CONTAINER_NAME}
    volumes:
      - ${REDIS_5_PATH}/data:/bitnami/redis/data
    ports:
      - "${REDIS_5_PORT}:6379"
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=${REDIS_NODES}
    networks:
      backend:
        ipv4_address: ${REDIS_5_IP}

  redis6:
    build:
      context: ./redis-cluster
      args:
        REDIS_CLUSTER_VERSION: ${REDIS_CLUSTER_VERSION}
    container_name: ${REDIS_6_CONTAINER_NAME}
    hostname: ${REDIS_6_CONTAINER_NAME}
    volumes:
      - ${REDIS_6_PATH}/data:/bitnami/redis/data
    ports:
      - "${REDIS_6_PORT}:6379"
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=${REDIS_NODES}
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes
    networks:
      backend:
        ipv4_address: ${REDIS_6_IP}