version: '3.8'

networks:
  flink-network:
    driver: bridge

services:
  flink:
    build:
      context: ./dockerfile
    hostname: flink
    container_name: flink
    ports:
      - "${flink}:443"
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ./www/:/var/www:cached
    networks:
      flink-network: