version: '3.8'

networks:
  rocketmq-standalone-network:
    driver: bridge

services:
  rocketmq-nameserver1:
    build:
      context: ./nameserver1
      args:
        ROCKETMQ_IMAGE: ${ROCKETMQ_IMAGE}
        ROCKETMQ_VERSION: ${ROCKETMQ_VERSION}
    hostname: rocketmq-nameserver1
    container_name: rocketmq-nameserver1
    ports:
      - ${NAMESRV_PORT}:${NAMESRV_PORT}
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m -Xmn128m
      - TZ=${TZ}
    volumes:
      - ./nameserver1/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      - rocketmq-standalone-network

  rocketmq-broker1:
    build:
      context: ./broker1
      args:
        ROCKETMQ_IMAGE: ${ROCKETMQ_IMAGE}
        ROCKETMQ_VERSION: ${ROCKETMQ_VERSION}
    hostname: rocketmq-broker1
    container_name: rocketmq-broker1
    volumes:
      - ./broker1/logs:/home/rocketmq/logs
      - ./broker1/store:/home/rocketmq/store
      - ./broker1/conf/broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    environment:
      - NAMESRV_ADDR=${NAMESRV_ADDR}
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m -Xmn128m
      - TZ=${TZ}
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    command: sh mqbroker -c /opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    depends_on:
      - rocketmq-nameserver1
    networks:
      - rocketmq-standalone-network

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    hostname: rocketmq-dashboard
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=${NAMESRV_ADDR}; -Xms256m -Xmx256m
    depends_on:
      - rocketmq-nameserver1
    networks:
      - rocketmq-standalone-network