version: '3.8'

networks:
  openresty-network:
    driver: bridge

services:
  openresty:
    build:
      context: ./openresty
    hostname: openresty
    container_name: openresty
    volumes:
      - ./var/www:/var/www:cached
      - ./openresty/logs/:/usr/local/openresty/nginx/logs
      - ./openresty/sites/:/etc/nginx/sites-available
      - ./openresty/ssl/:/etc/nginx/ssl
      - ./openresty/lua/:/usr/local/openresty/nginx/lua/
    environment:
      - TZ=${TZ}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - openresty-network