version: '3.8'

networks:
  backend:
    external: true

services:
  maildev:
    build:
      context: ./maildev
    hostname: maildev
    container_name: maildev
    ports:
      - "${MAILDEV_HTTP_PORT}:1080"
      - "${MAILDEV_SMTP_PORT}:1025"
    environment:
      - TZ=${TZ}
    networks:
      backend:
        ipv4_address: ${MAIL_DEV_IP}