version: '3.8'

networks:
  backend:
    external: true

services:
  ssdb:
    build:
      context: ./ssdb
    container_name: ssdb
    hostname: ssdb
    environment:
      - TZ=${TZ}
    volumes:
      - ./data:/data
    ports:
      - "${SSDB_PORT}:8888"
    networks:
      backend:
        ipv4_address: ${SSDB_IP}