version: '3.8'

volumes:
  gitlab:
    driver: ${VOLUMES_DRIVER}

configs:
  gitlab_rb:
    file: ../gitlab/config/gitlab.rb
secrets:
  gitlab_root_password:
    file: ../gitlab/config/root_password.txt

services:

### Gitlab ################################################
  gitlab:
    build:
      context: ../gitlab
      args:
        - GITLAB_VERSION=${GITLAB_VERSION}
    container_name: ${GITLAB_CONTAINER_NAME}
    hostname: ${GITLAB_HOSTNAME}
    environment:
      # GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_DOMAIN_NAME}'
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_HOST_SSH_PORT}
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gravatar_plain_url'] = 'http://sdn.geekzu.org/avatar/%{hash}?s=%{size}&d=identicon'
        gitlab_rails['gravatar_ssl_url'] = 'https://sdn.geekzu.org/avatar/%{hash}?s=%{size}&d=identicon'
    configs:
      - source: gitlab_rb
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    ports:
      - "${GITLAB_HOST_HTTP_PORT}:80"
      - "${GITLAB_HOST_HTTPS_PORT}:443"
      - "${GITLAB_HOST_SSH_PORT}:22"
    volumes:
      - ${DATA_PATH_HOST}/gitlab/config:/etc/gitlab
      - ${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab
      - ${GITLAB_HOST_LOG_PATH}:/var/log/gitlab
    shm_size: '1gb'
    logging: 
      driver: "json-file"
      options: 
        max-size: "2g"
        max-file: "2"
    networks:
      frontend:
        ipv4_address: ${GITLAB_FRONTEND_IP}
      backend:
        ipv4_address: ${GITLAB_BACKEND_IP}