version: '3.8'

volumes:
  soketi:
    driver: ${VOLUMES_DRIVER}

services:

### Soketi Server ########################################
  soketi:
    build:
      context: ../soketi
      args:
        - SOKETI_VERSION=${SOKETI_VERSION}
    container_name: ${SOKETI_CONTAINER_NAME}
    hostname: ${SOKETI_HOSTNAME}
    privileged: true
    volumes:
      - "${SOKETI_PATH_HOST}/config.json:/app/bin/config.json:ro"
    ports:
      - "${SOKETI_HOST_PORT}:6001"
      - "${SOKETI_METRICS_SERVER_PORT}:9601"
    networks:
      frontend:
        ipv4_address: ${SOKETI_FRONTEND_IP}
      backend:
        ipv4_address: ${SOKETI_BACKEND_IP}