version: '3.8'

volumes:
  beanstalkd:
    driver: ${VOLUMES_DRIVER}

services:

### Beanstalkd ###########################################
  beanstalkd:
    build:
      context: ../beanstalkd
      args:
        - BEANSTALKD_VERSION=${BEANSTALKD_VERSION}
    container_name: ${BEANSTALKD_CONTAINER_NAME}
    hostname: ${BEANSTALKD_HOSTNAME}
    privileged: true
    ports:
      - "${BEANSTALKD_HOST_PORT}:11300"
    environment:
      - TZ=${TZ}
    networks:
      frontend:
          ipv4_address: ${BEANSTALKD_FRONTEND_IP}
      backend:
        ipv4_address: ${BEANSTALKD_BACKEND_IP}