version: '3.8'

volumes:
  redismod:
    driver: ${VOLUMES_DRIVER}

services:

### RedisMod ################################################
  redismod:
    build:
      context: ../redis/redismod
      args:
        - REDISMOD_VERSION=${REDIS_VERSION}
    hostname: ${REDISMOD_HOSTNAME}
    container_name: ${REDISMOD_CONTAINER_NAME}
    volumes:
      - ${DATA_PATH_HOST}/redismod/data:/data
      - ${DATA_PATH_HOST}/redismod/logs:/var/log/redis
    ports:
      - "${REDISMOD_PORT}:6379"
    environment:
      - TZ=${TZ}
    networks:
      frontend:
        ipv4_address: ${REDISMOD_FRONTEND_IP}
      backend:
        ipv4_address: ${REDISMOD_BACKEND_IP}