version: '3.8'

volumes:
  nginx:
    driver: ${VOLUMES_DRIVER}

services:

### Nginx Server #########################################
  nginx:
    build:
      context: ../nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: ${NGINX_CONTAINER_NAME}
    hostname: ${NGINX_HOSTNAME}
    environment:
      - TZ=${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${LOG_PATH_HOST}/nginx:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "8212:8212"
      - "8222:8222"
      - "8211:8211"
      - "8213:8213"
      - "8223:8223"
      - "8231:8231"
      - "8224:8224"
      - "8221:8221"
      - "8242:8242"
    networks:
      frontend:
        ipv4_address: ${NGINX_FRONTEND_IP}
      backend:
        ipv4_address: ${NGINX_BACKEND_IP}