version: '3.8'

volumes:
  jenkins:
    driver: ${VOLUMES_DRIVER}

services:

### Jenkins ################################################
  jenkins:
    build:
      context: ../jenkins
      args:
        - JENKINS_SOURCES_LIST=${JENKINS_SOURCES_LIST}
        - JENKINS_REPLACE_SOURCES=${JENKINS_REPLACE_SOURCES}
        - JENKINS_ADD_DOCKER_SOURCES=${JENKINS_ADD_DOCKER_SOURCES}
        - JENKINS_VERSION=${JENKINS_VERSION}
        - JENKINS_DO_TIME_SYNC=${JENKINS_DO_TIME_SYNC}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    container_name: ${JENKINS_CONTAINER_NAME}
    hostname: ${JENKINS_HOSTNAME}
    privileged: true
    ports:
      - "${JENKINS_HOST_SLAVE_AGENT_PORT}:50000"
      - "${JENKINS_HOST_HTTP_PORT}:8080"
    volumes:
      - ${DATA_PATH_HOST}/jenkins/${JENKINS_HOME}:/var/jenkins_home
      - ${DOCKER_SOCK_HOST}:/var/run/docker.sock
    networks:
      frontend:
        ipv4_address: ${JENKINS_FRONTEND_IP}
      backend:
        ipv4_address: ${JENKINS_BACKEND_IP}