version: '3.8'

volumes:
  soketi:
    driver: ${VOLUMES_DRIVER}

services:

### Soketi Server ########################################
  soketi:
    build:
      context: ../soketi
      args:
        - BUSYBOX_VERSION=${BUSYBOX_VERSION}
    container_name: ${BUSYBOX_CONTAINER_NAME}
    hostname: ${BUSYBOX_HOSTNAME}
    privileged: true
    stdin_open: true
    tty: true
    networks:
      frontend:
          ipv4_address: ${BUSYBOX_FRONTEND_IP}
      backend:
        ipv4_address: ${BUSYBOX_BACKEND_IP}