version: "3.8"

networks:
  canal-cluster-network:

services:
  canal-server:
    build:
      context: ./canal-server
      args:
        CANAL_VERSION: ${CANAL_VERSION}
    hostname: canal-server
    container_name: canal-server
    ports:
      - "5005:5005"
      - "11110:11110" # admin
      - "11111:11111" # canal
      - "11112:11112" # metrics
      - "9100:9100"   # exporter
#    environment:
#      - canal.destinations=test-demo
#      - canal.auto.scan=false
#      - canal.instance.master.address=canal-mysql:3306
#      - canal.instance.dbUsername=canal
#      - canal.instance.dbPassword=canal
#      - canal.instance.connectionCharset=UTF-8
#      - canal.instance.tsdb.enable=true
#      - canal.instance.gtidon=true
    volumes:
      - ./canal-server/conf/test-demo/instance.properties:/home/admin/canal-server/conf/test-demo/instance.properties
      - ./canal-server/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./canal-server/logs:/home/admin/canal-server/logs
    depends_on:
      - canal-mysql
    networks:
      - canal-cluster-network

  canal-mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    hostname: canal-mysql
    container_name: canal-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    networks:
      - canal-cluster-network

  canal-admin:
    build:
      context: ./canal-admin
      args:
        CANAL_VERSION: ${CANAL_VERSION}
    hostname: canal-admin
    container_name: canal-admin
    ports:
      - "8089:8089"
    volumes:
      - ./canal-admin/conf/application.yml:/canal-admin/conf/application.yml
      - ./canal-admin/conf/canal-template.properties:/home/admin/canal-admin/conf/canal-template.properties
      - ./canal-admin/conf/instance-template.properties:/home/admin/canal-admin/conf/instance-template.properties
      - ./canal-admin/logs:/home/admin/canal-admin/logs
    depends_on:
      - canal-mysql
    networks:
      - canal-cluster-network

#  canal-adapter:
#    build:
#      context: ./canal-adapter
#      args:
#        CANAL_VERSION: ${CANAL_VERSION}
#    hostname: canal-adapter
#    container_name: canal-adapter
#    ports:
#      - "8081:8081"
#    volumes:
#      - ./canal-adapter/conf/application.yml:/canal-adapter/conf/application.yml
#      - ./canal-adapter/conf/bootstrap.yml:/canal-adapter/conf/bootstrap.yml
#    networks:
#      - canal-network